### ISSUE TITLE
'crl test' fails with check-manifest==0.42

### ISSUE THREAD

**Issue by vereszol** [nokia/crl-devutils#15]
Check-manifest dropped python2 support with [version 0.42](https://github.com/mgedmin/check-manifest/blob/master/CHANGES.rst#042-2020-05-03).

This is a backwards incompatible change, which is making **devpi upload** failing with following error:

> cmd: devpi upload --clientdir /tmp/jenkins_utzsvvyuxh
> stdout:
> detected devpi:upload section in /mnt/work/workspace/Merge/crl-xyz-pre-merge/setup.cfg
> 
> stderr:
> Traceback (most recent call last):
>   File "/mnt/work/workspace/Merge/crl-xyz-pre-merge/.tox/test/bin/devpi", line 8, in <module>
>     sys.exit(main())
>   File "/mnt/work/workspace/Merge/crl-xyz-pre-merge/.tox/test/lib/python3.7/site-packages/devpi/main.py", line 36, in main
>     return method(hub, hub.args)
>   File "/mnt/work/workspace/Merge/crl-xyz-pre-merge/.tox/test/lib/python3.7/site-packages/devpi/upload.py", line 34, in main
>     setupdir_only=setupcfg.get("setupdir-only"))
>   File "/mnt/work/workspace/Merge/crl-xyz-pre-merge/.tox/test/lib/python3.7/site-packages/devpi/upload.py", line 282, in __init__
>     hasvcs = check_manifest.detect_vcs().metadata_name
> TypeError: detect_vcs() missing 1 required positional argument: 'ui'
> 
> returncode: 1

This leads to  **crl test** fail as well.

**Comment by vereszol** [comment]
This is a duplicate of #18
